joy_teleop:
  ros__parameters:

    move:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: cmd_vel
      deadman_buttons: [0]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 1.0
          offset: 0.0
        linear-y:
          axis: 2
          scale: 1.0
          offset: 0.0
